-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("FileType", {
--     pattern = "c",
--     callback = function()
--         vim.api.nvim_set_keymap(
--             "n",
--             "<Leader>w",
--             -- ":w <CR>:!gcc % -O2 -std=c11 -g -o %:r.out && ./%:r.out<CR>",
--             ":w <CR>:!gcc % -O2 -std=c11 -g -o %:r.out<CR>",
--             { noremap = true, silent = true }
--         )
--     end,
-- })
